name: spensr
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^4.0.4
  firebase_core: ^2.25.0
  firebase_auth: ^4.17.0

  # STATE MANAGEMENT
  provider: ^6.1.2   # ‚Üê ADD THIS HERE

  # ROUTING
  auto_route: ^7.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  # CODE GENERATION (correct version)
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/images/
